management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always


file:
  transmission:
    upload:
      path: E:\enterprise-data\upload\

spring:
  servlet:
    multipart:
      max-file-size: 30GB
      max-request-size: 50GB
